Repository PNUMeat/comon-be, pull requests merged in 2024-12, with the labels that each got.

#31 [스프린트 3] 강수민 - 팀 생성 기능 추가
  src/main/java/PNUMEAT/Backend/domain/auth/entity/Member.java
  src/main/java/PNUMEAT/Backend/domain/team/controller/TeamController.java
  src/main/java/PNUMEAT/Backend/domain/team/dto/request/TeamRequest.java
  src/main/java/PNUMEAT/Backend/domain/team/entity/Team.java
  src/main/java/PNUMEAT/Backend/domain/team/enums/Topic.java
  src/main/java/PNUMEAT/Backend/domain/team/repository/TeamRepository.java
  src/main/java/PNUMEAT/Backend/domain/team/service/TeamService.java
  src/main/java/PNUMEAT/Backend/domain/team_member/entity/TeamMember.java
  src/main/java/PNUMEAT/Backend/domain/team_member/repository/TeamMemberRepository.java
  src/main/java/PNUMEAT/Backend/global/error/ErrorCode.java
  src/main/java/PNUMEAT/Backend/global/response/ResponseMessageEnum.java
  src/main/java/PNUMEAT/Backend/global/validation/annotation/NotNullOrBlank.java
  src/main/java/PNUMEAT/Backend/global/validation/validator/NotNullOrBlankValidator.java
  src/test/java/PNUMEAT/Backend/domain/team/service/TeamServiceTest.java
Labels: 기능

#33 [스프린트3 - 강수민] 최대인원 검증 로직 오류 수정
  src/main/java/PNUMEAT/Backend/BackendApplication.java
  src/main/java/PNUMEAT/Backend/domain/auth/entity/Member.java
  src/main/java/PNUMEAT/Backend/domain/team/dto/request/TeamRequest.java
  src/main/java/PNUMEAT/Backend/domain/team/entity/Team.java
  src/main/java/PNUMEAT/Backend/domain/team/enums/Topic.java
  src/main/java/PNUMEAT/Backend/domain/team/service/TeamService.java
  src/main/java/PNUMEAT/Backend/domain/teamMember/entity/TeamMember.java
  src/main/java/PNUMEAT/Backend/domain/teamMember/repository/TeamMemberRepository.java
  src/main/java/PNUMEAT/Backend/global/util/TimeStamp.java
  src/test/java/PNUMEAT/Backend/domain/team/service/TeamServiceTest.java
Labels: 버그, 리팩터링

#34 [스프린트 3] 장진영 - 코드 리팩토링
  build.gradle
  src/main/java/PNUMEAT/Backend/BackendApplication.java
  src/main/java/PNUMEAT/Backend/domain/auth/controller/AuthApiController.java
  src/main/java/PNUMEAT/Backend/domain/auth/controller/AuthController.java
  src/main/java/PNUMEAT/Backend/domain/auth/controller/LoginController.java
  src/main/java/PNUMEAT/Backend/domain/auth/entity/Member.java
  src/main/java/PNUMEAT/Backend/domain/team/entity/Team.java
  src/main/java/PNUMEAT/Backend/domain/team/enums/Topic.java
  src/main/java/PNUMEAT/Backend/global/error/ComonException.java
  src/main/java/PNUMEAT/Backend/global/error/ErrorCode.java
  src/main/java/PNUMEAT/Backend/global/error/GlobalExceptionHandler.java
  src/main/java/PNUMEAT/Backend/global/error/dto/response/ApiResponse.java
  src/main/java/PNUMEAT/Backend/global/error/images/ImageFileDeleteException.java
  src/main/java/PNUMEAT/Backend/global/error/images/ImageFileUploadException.java
  src/main/java/PNUMEAT/Backend/global/error/images/S3Exception.java
  src/main/java/PNUMEAT/Backend/global/security/configuration/CorsConfiguration.java
  src/main/java/PNUMEAT/Backend/global/security/configuration/SecurityConfiguration.java
  src/main/java/PNUMEAT/Backend/global/security/filter/JWTAccessFilter.java
  src/main/java/PNUMEAT/Backend/global/security/filter/JWTLogoutFilter.java
  src/main/java/PNUMEAT/Backend/global/security/filter/JWTRefreshFilter.java
  src/main/java/PNUMEAT/Backend/global/security/utils/servletUtils/cookie/CookieUtils.java
  src/main/java/PNUMEAT/Backend/global/security/utils/servletUtils/jwtUtils/FilterResponseUtils.java
  src/main/resources/application.properties
  src/test/java/PNUMEAT/Backend/global/security/filter/JWTAccessFilterTest.java
  src/test/java/PNUMEAT/Backend/global/security/filter/JWTLogoutFilterTest.java
  src/test/java/PNUMEAT/Backend/global/security/filter/JWTRefreshFilterTest.java
  src/test/resources/application.properties
Labels: 리팩터링

#35 [스프린트 3] 장진영 - #36 이슈 해결
  src/main/java/PNUMEAT/Backend/domain/team/controller/TeamController.java
Labels: 버그

#37 [스프린트 4] 장진영 - 회원 프로필 API 기능 개발
  src/main/java/PNUMEAT/Backend/domain/auth/controller/AuthApiController.java
  src/main/java/PNUMEAT/Backend/domain/auth/controller/MemberController.java
  src/main/java/PNUMEAT/Backend/domain/auth/dto/request/MemberProfileCreateRequest.java
  src/main/java/PNUMEAT/Backend/domain/auth/dto/request/MemberProfileUpdateRequest.java
  src/main/java/PNUMEAT/Backend/domain/auth/dto/response/MemberProfileResponse.java
  src/main/java/PNUMEAT/Backend/domain/auth/entity/Member.java
  src/main/java/PNUMEAT/Backend/domain/auth/service/MemberService.java
  src/main/java/PNUMEAT/Backend/global/error/ErrorCode.java
  src/main/java/PNUMEAT/Backend/global/error/Member/MemberNotFoundException.java
  src/main/java/PNUMEAT/Backend/global/error/Member/MemberProfileUpdateValidException.java
  src/main/java/PNUMEAT/Backend/global/error/Member/UnauthorizedException.java
  src/main/java/PNUMEAT/Backend/global/error/user/UnauthorizedException.java
  src/main/java/PNUMEAT/Backend/global/security/configuration/SecurityConfiguration.java
  src/main/java/PNUMEAT/Backend/global/security/filter/JWTAccessFilter.java
  src/test/java/PNUMEAT/Backend/domain/auth/service/MemberServiceTest.java
  src/test/java/PNUMEAT/Backend/global/security/filter/JWTAccessFilterTest.java
Labels: 기능

#38 [스프린트 4] 장진영 - Refresh Token을 활용한 사용자 경험 개선 기능 추가
  src/main/java/PNUMEAT/Backend/domain/auth/controller/AuthApiController.java
  src/main/java/PNUMEAT/Backend/global/security/oauth/OAuth2SuccessHandler.java
  src/main/java/PNUMEAT/Backend/global/security/utils/servletUtils/cookie/CookieUtils.java
Labels: 기능

#39 [스프린트 4] 장진영 - 사용하지 않는 Class 삭제
  src/main/java/PNUMEAT/Backend/TestController.java
  src/main/java/PNUMEAT/Backend/domain/article/controller/ArticleController.java
  src/main/java/PNUMEAT/Backend/domain/team/controller/TeamController.java
  src/main/java/PNUMEAT/Backend/global/error/user/UserNotFoundException.java
  src/main/java/PNUMEAT/Backend/global/images/ImageController.java
Labels: 버그

#41 [스프린트 4] 장진영 - 회원 프로필 버그 수정
  src/main/java/PNUMEAT/Backend/domain/auth/entity/Member.java
Labels: 버그

#43 [스프린트 4] 강수민 - 팀 조회하기 API 구현
  src/main/java/PNUMEAT/Backend/domain/team/controller/TeamController.java
  src/main/java/PNUMEAT/Backend/domain/team/dto/response/MyTeamResponse.java
  src/main/java/PNUMEAT/Backend/domain/team/dto/response/TeamAllResponse.java
  src/main/java/PNUMEAT/Backend/domain/team/dto/response/TeamCombinedResponse.java
  src/main/java/PNUMEAT/Backend/domain/team/entity/Team.java
  src/main/java/PNUMEAT/Backend/domain/team/repository/TeamRepository.java
  src/main/java/PNUMEAT/Backend/domain/team/service/TeamService.java
  src/main/java/PNUMEAT/Backend/domain/teamMember/entity/TeamMember.java
  src/main/java/PNUMEAT/Backend/domain/teamMember/repository/TeamMemberRepository.java
  src/main/java/PNUMEAT/Backend/global/response/ResponseMessageEnum.java
  src/main/java/PNUMEAT/Backend/global/security/configuration/JpaAuditingConfiguration.java
  src/main/java/PNUMEAT/Backend/global/security/configuration/WebConfig.java
  src/test/java/PNUMEAT/Backend/domain/team/repository/TeamRepositoryTest.java
  src/test/java/PNUMEAT/Backend/domain/team/service/TeamServiceTest.java
  src/test/java/PNUMEAT/Backend/domain/teamMember/repository/TeamMemberRepositoryTest.java
Labels: 기능

#44 [스프린트 4] 강수민 - 팀 가입하기 API 구현
  src/main/java/PNUMEAT/Backend/domain/team/controller/TeamController.java
  src/main/java/PNUMEAT/Backend/domain/team/dto/request/TeamJoinRequest.java
  src/main/java/PNUMEAT/Backend/domain/team/service/TeamService.java
  src/main/java/PNUMEAT/Backend/domain/teamMember/repository/TeamMemberRepository.java
  src/main/java/PNUMEAT/Backend/global/error/ErrorCode.java
  src/main/java/PNUMEAT/Backend/global/error/Team/TeamAlreadyJoinException.java
  src/main/java/PNUMEAT/Backend/global/error/Team/TeamNotFoundException.java
  src/main/java/PNUMEAT/Backend/global/error/Team/TeamPasswordInvalidException.java
  src/main/java/PNUMEAT/Backend/global/response/ResponseMessageEnum.java
  src/main/resources/application.properties
  src/test/java/PNUMEAT/Backend/domain/team/service/TeamServiceTest.java
Labels: 기능

#59 [스프린트 5] 장진영 - 팀장 페이지 기능 구현
  src/main/java/PNUMEAT/Backend/domain/article/controller/ArticleController.java
  src/main/java/PNUMEAT/Backend/domain/article/dto/request/CalenderSubjectRequest.java
  src/main/java/PNUMEAT/Backend/domain/article/dto/response/CalenderSubjectResponse.java
  src/main/java/PNUMEAT/Backend/domain/article/dto/response/SubjectArticleDateAndTagResponse.java
  src/main/java/PNUMEAT/Backend/domain/article/repository/ArticleRepository.java
  src/main/java/PNUMEAT/Backend/domain/article/service/ArticleService.java
  src/test/java/PNUMEAT/Backend/domain/article/repository/ArticleRepositoryTest.java
Labels: 기능

#62 [스프린트 5] 강수민 - 팀 게시물 조회 기능 수정 및 테스트 이름 수정
  src/main/java/PNUMEAT/Backend/domain/article/controller/ArticleController.java
  src/main/java/PNUMEAT/Backend/domain/article/dto/response/ArticleResponse.java
  src/main/java/PNUMEAT/Backend/domain/team/controller/TeamController.java
  src/main/java/PNUMEAT/Backend/domain/team/dto/response/TeamJoinResponse.java
  src/test/java/PNUMEAT/Backend/domain/article/repository/ArticleRepositoryTest.java
  src/test/java/PNUMEAT/Backend/domain/article/service/ArticleServiceTest.java
Labels: 리팩터링

#66 [스프린트 5] - 강수민 팀 가입 시, 데이터와 메시지 동시에 가도록 수정
  src/main/java/PNUMEAT/Backend/domain/article/controller/ArticleController.java
  src/main/java/PNUMEAT/Backend/domain/auth/controller/MemberController.java
  src/main/java/PNUMEAT/Backend/domain/team/controller/TeamController.java
  src/main/java/PNUMEAT/Backend/global/error/dto/response/ApiResponse.java
Labels: 기능

#67 [스프린트 5] 강수민 - 나의 팀 조회 시 모든 팀 반환
  src/main/java/PNUMEAT/Backend/domain/team/dto/response/MyTeamResponse.java
  src/main/java/PNUMEAT/Backend/domain/team/repository/TeamRepository.java
  src/main/java/PNUMEAT/Backend/domain/team/service/TeamService.java
  src/main/java/PNUMEAT/Backend/domain/teamMember/repository/TeamMemberRepository.java
  src/main/java/PNUMEAT/Backend/domain/teamMember/service/TeamMemberService.java
  src/test/java/PNUMEAT/Backend/domain/team/repository/TeamRepositoryTest.java
  src/test/java/PNUMEAT/Backend/domain/team/service/TeamServiceTest.java
  src/test/java/PNUMEAT/Backend/domain/teamMember/repository/TeamMemberRepositoryTest.java
Labels: 기능

#68 [스프린트 5] 강수민 - 팀 주제 조회 API 수정
  src/main/java/PNUMEAT/Backend/domain/article/controller/ArticleController.java
  src/main/java/PNUMEAT/Backend/domain/article/dto/response/TeamSubjectResponse.java
Labels: 기능
